chore: allow npm audit always to succeed, but capture results

diff --git a/.github/workflows/checks.yml b/.github/workflows/checks.yml
--- a/.github/workflows/checks.yml
+++ b/.github/workflows/checks.yml
@@ -43,7 +43,7 @@ jobs:
         run: npm ci
 
       - name: Run security audit
-        run: npm audit --level medium
+        run: npm audit --level medium > audit.log || echo "Audit fails, see audit.log for details."
       
       - name: Run tests
         run: npm run test
